services:
  securestorage:
    build:
       context: .
       dockerfile: SecureStorage/Dockerfile
    ports:
      - "32773:443"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - Keycloak__Authority=http://keycloak:8080/realms/securestorage
      # ADD SECRETS HERE
      - AZURE_CLIENT_ID=
      - AZURE_TENANT_ID=
      - AZURE_CLIENT_SECRET=
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https:ro
    depends_on:
      - openfga
      - keycloak  
    networks:
      - openfga-network

  postgres:
    image: postgres:15
    container_name: openfga-postgres
    environment:
      - POSTGRES_USER=openfga
      - POSTGRES_PASSWORD=openfga
      - POSTGRES_DB=openfga
    ports:
      - "5432:5432"
    volumes:
      - openfga_pg_data:/var/lib/postgresql/data
    networks:
      - openfga-network

  openfga-migrate:
    image: openfga/openfga:v1.5.3
    command: migrate
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://openfga:openfga@postgres:5432/openfga?sslmode=disable
    depends_on:
      - postgres
    networks:
      - openfga-network
    restart: "no"

  openfga:
    image: openfga/openfga:v1.5.3
    container_name: openfga
    command: run
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_PLAYGROUND_ENABLED=true
      - OPENFGA_DATASTORE_URI=postgres://openfga:openfga@postgres:5432/openfga?sslmode=disable
    depends_on:
      - openfga-migrate
    ports:
      - "8080:8080"
      - "8081:8081"
      - "3000:3000"
    networks:
      - openfga-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    command: start-dev --db=postgres --hostname-strict=false 
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=secret
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=postgres
      - KC_DB_USERNAME=openfga
      - KC_DB_PASSWORD=openfga
      - QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY=true
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    networks:
      - openfga-network
    volumes:
      - keycloak_data:/opt/keycloak/data
networks:
  openfga-network:
    driver: bridge

volumes:
  openfga_pg_data:
  keycloak_data: